!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.23.0.dev0+98.g0e10696f5)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitvec(f2pysetupfunc)
      use vec, only : unit_move
      external f2pysetupfunc
      call f2pysetupfunc(unit_move)
      end subroutine f2pyinitvec


