name: CI

on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.9"]
        poetry-version: [1.1.11, 1.1.12]
        os: [ubuntu-18.04] #, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get dependencies
        run: |
            sudo apt-get -qq update
            sudo apt-get -y install build-essential libopenblas-dev gfortran-10
      - name: Get repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0 # Fetch all history

      - name: Grab Python
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: Get Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install deps
        run: poetry install

      - name: Test
        run: poetry run pytest
