name: pytest-coverage-commentator
on:
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get dependencies
      run: |
          sudo apt-get -qq update
          sudo apt-get -y install build-essential libopenblas-dev gfortran-10
    - name: Get repo
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0 # Fetch all history

    - name: Grab Python
      uses: actions/setup-python@v2
      with:
          python-version: "3.10"

    - name: Get Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.12"

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Build coverage file
      run: |
          poetry run pytest --cache-clear --cov=f2py_skel tests/ > pytest-coverage.txt

    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
